language: python
python:
  - "3.7" 
branches:
  only:
    - master
install: pip3 install --upgrade pip
script: flask run
notifications: # success or not
  email:
    recipients:
      - dongjinmedia@gmail.com