language: python
python:
  - "3.7" 
script:
  - echo "skipping tests"
branches:
  only:
    - master
before_deploy:
  - rm -rf node_modules 
  - zip -r bigpoint *
  - mkdir -p deploy
  - mv bigpoint.zip deploy/bigpoint.zip 

deploy: 
  - provider: s3 
    access_key_id: AKIA5QF5QPF5GNWTXGPY
    secret_access_key: 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
    bucket: bigpoint3
    region: ap-northeast-2
    skip_cleanup: true 
    local_dir: deploy 
    wait-until-deployed: true
    on:
      repo: Dongjinmedia/Bigpoint
      branch: master
  - provider: codedeploy
    access_key_id: AKIA5QF5QPF5GNWTXGPY
    secret_access_key: 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 
    bucket: bigpoint3 # AWS CodeDeploy가 다운로드 받은 버킷
    key: bigpoint.zip # 해당 버킷에 저장되어 있는 파일 이름
    bundle_type: zip # 버킷에 저장되어 있는 파일의 확장자
    application: code_deploy_service 
    deployment_group: deploy_group 
    region: ap-northeast-2
    file_glob: true
    file:
    - deploy/*.zip
    file: ${PROJECT_NAME}-${TRAVIS_TAG}-${TARGET}.*
    skip_cleanup: true
    wait-until-deployed: true
    on:
      repo: Dongjinmedia/Bigpoint
      branch: master

after_deploy:
  - ./docker-compose up -d